In [2]:
import pandas as pd
import pickle as pk
import numpy as np

#### Prueba de cosas 

In [30]:
data = pd.read_pickle("../dataset/data_global.pkl")
data

pf type
source_id                         
184457373509254272   3.406982  ECL
187514458214460928   0.689039  ECL
193720243577690880   3.335009  ECL
204067060310941696   1.849591  ECL
251636125219970816   0.426586  ECL
...                       ...  ...
6061643754695131008  0.730192   RR
6061651004600021888  0.498657   RR
6061675365655690624  0.474386   RR
6061700551345078912  0.652145   RR
6061867986376466688  0.766155   RR

[200 rows x 2 columns]

In [75]:
data_global[data_global.index == int('184457373509254272')].values[0][0]

3.4069816204289323

In [13]:
dict_per = pd.read_pickle('../dataset/ECL/184457373509254272/periodograms.pkl')
band = 'BP'
per = dict_per[band]
freq = pd.read_pickle('../dataset/ECL/frequencies_ECL.pkl')
data_global = pd.read_pickle('../dataset/data_global.pkl')
name_lc = '184457373509254272'
lc = pd.read_pickle('../dataset/ECL/184457373509254272/184457373509254272.pkl')
name_lc = lc.source_id.iloc[0]
period = data_global[data_global.index == name_lc].values[0][0]
1/period           


0.29351493826788005

In [73]:
freq

array([1.473000e-03, 1.573000e-03, 1.673000e-03, ..., 9.999573e+00,
       9.999673e+00, 9.999773e+00])

In [ ]:
freq_real-(tol/2) < freq < freq_real+(tol/2)

Analisis para la tolerancia
|freq-fr|/fr < tol

In [76]:
band

'BP'

In [79]:
top = 10
type = "ECL"
path = '../dataset/ECL/184457373509254272/periodograms.pkl'
dict_per = pd.read_pickle(path)
per = dict_per[band]
local_maxima = np.where((per[1:-1] > per[:-2]) & (per[1:-1] > per[2:]))[0] + 1
idx_highest = local_maxima[np.argsort(per[local_maxima])[::-1]]

period = data_global[data_global.index == 184457373509254272].values[0][0]

for k, idx_ in enumerate(idx_highest[:top]):
    #ax.axvline(freq[idx_], ls='--', lw=2, alpha=0.5, c='k') 
    print(f'Ranking: {k+1} Frequency: {freq[idx_]:0.4f} Power: {per[idx_]:0.4f}')


Ranking: 1 Frequency: 1.2902 Power: 0.6769
Ranking: 2 Frequency: 0.7261 Power: 0.6498
Ranking: 3 Frequency: 0.3116 Power: 0.6226
Ranking: 4 Frequency: 1.0533 Power: 0.6085
Ranking: 5 Frequency: 0.3701 Power: 0.5951
Ranking: 6 Frequency: 1.9733 Power: 0.5729
Ranking: 7 Frequency: 0.8809 Power: 0.5388
Ranking: 8 Frequency: 1.0602 Power: 0.5381
Ranking: 9 Frequency: 0.0643 Power: 0.5314
Ranking: 10 Frequency: 1.6392 Power: 0.5234


In [81]:
idx_highest

array([12887,  7246,  3101, ..., 94640, 69133, 65562])

In [78]:
per

array([0.1447983 , 0.12472169, 0.11389534, ..., 0.041566  , 0.03039182,
       0.02039928])

In [66]:
freq[idx_]

1.6391730000000009

In [37]:
def relative_error(observed, actual):
    return np.absolute((observed - actual)/actual)

In [67]:
frequencies_ranking = idx_highest[:10]
error = relative_error(frequencies_ranking[top-1], period)
tol = 0.6
tol = error < tol
print(error, tol)

4805.894144013072 False


In [68]:
relative_error(frequencies_ranking[0], period)

3781.5270094581706

In [69]:
# columna de la matriz con multiplos y submultiplos
max = 4  # tamaño max-1 + max-2
multiples = np.concatenate([np.arange(1, max, 1), # multiples
                                1./np.arange(2, max, 1)]) # submultiples
multiples

array([1.        , 2.        , 3.        , 0.5       , 0.33333333])

In [8]:
# matriz[fila,columna]
# matriz[freq_rank, multiplo]

17

In [70]:
matrix = [ [ [] for i in range(5) ] for j in range(10) ]
matrix

[[[], [], [], [], []],
 [[], [], [], [], []],
 [[], [], [], [], []],
 [[], [], [], [], []],
 [[], [], [], [], []],
 [[], [], [], [], []],
 [[], [], [], [], []],
 [[], [], [], [], []],
 [[], [], [], [], []],
 [[], [], [], [], []]]

TypeError: 'list' object is not callable

In [57]:
matrix[0][1] = [1,2]
matrix

[[[], [1, 2], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], []]]

In [71]:
for i in range(len(frequencies_ranking)):
    for j in range(len(multiples)):
        error = relative_error(1/frequencies_ranking[i], period)
        tol = error<tol
        matrix[i][j] = [error, tol]

In [72]:
for i in range(10):
        for j in range(5):
            print(matrix[i][j], end=' ')
        print()

[0.9999772239514031, False] [0.9999772239514031, False] [0.9999772239514031, False] [0.9999772239514031, False] [0.9999772239514031, False] 
[0.9999594928321464, False] [0.9999594928321464, False] [0.9999594928321464, False] [0.9999594928321464, False] [0.9999594928321464, False] 
[0.9999053482946573, False] [0.9999053482946573, False] [0.9999053482946573, False] [0.9999053482946573, False] [0.9999053482946573, False] 
[0.9999720940351523, False] [0.9999720940351523, False] [0.9999720940351523, False] [0.9999720940351523, False] [0.9999720940351523, False] 
[0.999920370336878, False] [0.999920370336878, False] [0.999920370336878, False] [0.999920370336878, False] [0.999920370336878, False] 
[0.9999851143656422, False] [0.9999851143656422, False] [0.9999851143656422, False] [0.9999851143656422, False] [0.9999851143656422, False] 
[0.9999666232728829, False] [0.9999666232728829, False] [0.9999666232728829, False] [0.9999666232728829, False] [0.9999666232728829, False] 
[0.999972275910242